# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"
  
  config.vm.network "forwarded_port", guest: 80, host: 8085

  config.vbguest.auto_update = false

  config.vm.provision "file", source: "~/vagrant/files/git-config", destination: "~/.gitconfig"
  config.vm.provision "shell", path: "https://raw.githubusercontent.com/MikelSwartz/vagrant-LAMP-with-mysql-centos7/master/scripts/centos7-lamp.sh"

end
